custom:
  message: Centralized config for api gateway (including refresh scope)
server:
  port: 9000

spring:
  cloud:
    gateway:
      routes:
      - id: user-service
        uri: lb://user-service
        predicates:
        - Path=/users/**
        filters:
        - AuthenticationFilter

     - id: product-service
       uri: lb://product-service
       predicates:
       - Path=/products/**
       filters:
       - AuthenticationFilter

management:
  endpoints:
    web:
      exposure:
        include: health, info, gateway, refresh
