custom:
  message: Centralized config for api gateway (including refresh scope)
server:
  port: 9000

spring:
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/users/**
          filters:
            - AuthenticationFilter
        - id: product-service
          uri: lb://product-service
          predicates:
            - Path=/products/**
          filters:
            - AuthenticationFilter
        - id: product-detail-service
          uri: lb://product-detail-service
          predicates:
            - Path=/product-details/**
          filters:
            - AuthenticationFilter

eureka:
  client:
    serviceUrl:
      defaultZone: http://172.27.64.1:8761/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}

management:
  endpoints:
    web:
      exposure:
        include: health, info, gateway, refresh
  tracing:
    sampling:
      probability: 1.0  #Trace everything - 100%

zipkin:
  enabled: true
  base-url: http://localhost:9411/zipkin/
