custom:
  message: Centralized config for Inventory Service (including refresh scope)
server:
  port: 8084

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ecommerceinventorydb
    username: root
    password: admin
  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl:
        auto: update
  kafka:
    bootstrap-servers: localhost:9092
    template:
      observation-enabled: true
    listener:
      observation-enabled: true
    consumer:
      group-id: inventory-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"

eureka:
  client:
    serviceUrl:
      defaultZone: http://172.27.64.1:8761/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}

management:
  endpoints:
    web:
      exposure:
        include: health, info, gateway, refresh
  tracing:
    sampling:
      probability: 1.0  #Trace everything - 100%
    propagation:
      type: B3
    export:
      zipkin:
        enabled: true

zipkin:
  enabled: true
  base-url: http://localhost:9411/zipkin/
