custom:
  message: Centralized config for Product Detail Service (including refresh scope)
server:
  port: 8083

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ecommerceproductdetaildb
    username: root
    password: admin
  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl:
        auto: update

eureka:
  client:
    serviceUrl:
      defaultZone: http://172.27.64.1:8761/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}

management:
  endpoints:
    web:
      exposure:
        include: health, info, gateway, refresh
  tracing:
    sampling:
      probability: 1.0  #Trace everything - 100%

zipkin:
  enabled: true
  base-url: http://localhost:9411/zipkin/
